DROP DATABASE IF EXISTS exo_contacts;
CREATE DATABASE exo_contacts CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE exo_contacts;

CREATE TABLE contacts(
   id BIGINT PRIMARY KEY AUTO_INCREMENT,
   nom VARCHAR(70) NOT NULL,
   prenom VARCHAR(70),
   date_de_naissance DATETIME,
   sexe VARCHAR(10),
   adresse TEXT,
   cp VARCHAR(10),
   ville VARCHAR(70),
   pays_iso_3 VARCHAR(3),
   FOREIGN KEY (pays_iso_3) REFERENCES pays(iso_3),
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE telephone(
   id BIGINT PRIMARY KEY AUTO_INCREMENT,
   id_contact INT NOT NULL,
   numero VARCHAR(50) NOT NULL,
   le_type TINYINT,
   FOREIGN KEY (id_contact) REFERENCES contacts(id),
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE pays (
    iso_3 VARCHAR(3) PRIMARY KEY,
    nom VARCHAR(70) NOT NULL,
    iso_2 VARCHAR(2) NOT NULL,
    nationalite VARCHAR(50),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 